//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartaDePresentacion
    {
        public int CodCartaPresentacion { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<int> CodInforme { get; set; }
    
        public virtual Informe Informe { get; set; }
    }
}
