//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Informe()
        {
            this.CartaDePresentacion = new HashSet<CartaDePresentacion>();
            this.InformeAvanceEPP = new HashSet<InformeAvanceEPP>();
            this.InformeDeSupervisionEPP = new HashSet<InformeDeSupervisionEPP>();
            this.InformeFinalEPP = new HashSet<InformeFinalEPP>();
            this.PlanDeTrabajoEPP = new HashSet<PlanDeTrabajoEPP>();
        }
    
        public int CodInforme { get; set; }
        public string TipoInforme { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<System.DateTime> FechaDeSubida { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CodUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartaDePresentacion> CartaDePresentacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeAvanceEPP> InformeAvanceEPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeDeSupervisionEPP> InformeDeSupervisionEPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeFinalEPP> InformeFinalEPP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDeTrabajoEPP> PlanDeTrabajoEPP { get; set; }
    }
}
